### ISSUE TITLE
Typescript Version

### ISSUE THREAD

**Issue by sergiusignacius** [Forty-Niner/fate-lang#2]
Hey @kode4food,

What Typescript version are you using? I get a compilation error building the Compiler module.

```
fate-lang/lib/compiler/Compiler.ts(104,21): error TS2339: Property 'found' does not exist on type 'SyntaxError'.
fate-lang/lib/compiler/Compiler.ts(105,20): error TS2339: Property 'line' does not exist on type 'SyntaxError'.
fate-lang/lib/compiler/Compiler.ts(106,22): error TS2339: Property 'column' does not exist on type 'SyntaxError'.
```
Code emission succeeds and everything else runs.

Cheers,
Sérgio

**Comment by kode4food** [comment]
It should work with anything from TypeScript 1.5 and up.  Those errors are the result of the peg.js generating its own objects, but with no type information.  I could always coerce it into a home-made interface, but didn't really see it as a priority.

The error doesn't prohibit the final code gen... or at least it shouldn't in the versions of TypeScript I've used.

**Comment by sergiusignacius** [comment]
Yeah, code generation is ok. So this SyntaxError type is the peg.js one. It seems to resolve to Javascript's syntax error (defined in lib.d.ts).

Do you think it's worth it to use [pegjs.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pegjs/pegjs.d.ts)?

**Comment by kode4food** [comment]
what?  no!  that's just crazy!  didn't realize there was tsd info for it.  will add it now, thanks

**Comment by sergiusignacius** [comment]
No problem, I was gonna add it in my fork. :+1:

**Comment by kode4food** [comment]
done!  you may rebase, sir!

**Comment by sergiusignacius** [comment]
Cool! Thanks! :smile:
